# Generated by Django 3.2.12 on 2023-06-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['rating'], name='booking_use_rating_4b6a2e_idx'),
        ),
    ]
